### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by andruten**
Hi! 

Thank you for this repository. It helped me a lot :).

I'm trying to put my two cents in here. I've added docker support adding a Dockerfile (Alpine image with node 18) and a Makefile introducing four commands:
- `make build`: Build a docker image installing ffmpeg OS dependency
- `make start`: executes `npm run start`
- `make convert`: executes `npm run convert`
- `make bash`: Run sh command in a container

If you agree this feature, I can update the README as well.

### CODE REVIEW

**Comment by Tusko** [comment]
Great ideas, but add README, please.

I got an error while running Docker

CleanShot 2023-02-25 at 08 13 10@2x

P.S. Please do not forget to add instructions how to use with M1 processor

**Comment by andruten** [comment]
I'll update the README, sure. I can test in a M1 as well. I did it using a Mac with Intel chip. 

Thanks!

**Comment by andruten** [comment]
I've replaced the beluga test json url using
https://133vod-adaptive.akamaized.net/exp=1677316600~acl=%2Fd72c115f-b778-413c-98cb-b52877d91cbc%2F%2A~hmac=d5fde3ab15d0c48b15cd76e166bfbed047c6ab903d2dae75b8b661d2895c2035/d72c115f-b778-413c-98cb-b52877d91cbc/sep/video/b38809eb,c9f850d5,ba8684e0,24af147c,1dfa90ba,792b3ca4,d2b12077/audio/102b87bb,1c5d2276,aa1c00c3/master.json?query_string_ranges=1&base64_init=1 as the initial one says
```
→ ⚠️  The master.json file is expired or crushed. Please update or remove it from the sequence (broken on 0 position)
```

I tried in a M1 PRO and worked properly. Steps are: `make build`, `make start` and `make combine`.
```
$ make build
[+] Building 9.1s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                             0.0s
 => => transferring dockerfile: 181B                                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                                0.0s
 => => transferring context: 67B                                                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/node:18-alpine                                                                                                                                                1.9s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                                                      0.0s
 => [internal] load build context                                                                                                                                                                                0.0s
 => => transferring context: 99.78kB                                                                                                                                                                             0.0s
 => [1/6] FROM docker.io/library/node:18-alpine@sha256:0d2712ac2b2c1149391173de670406f6e3dbdb1b2ba44e8530647e623e0e1b17                                                                                          3.2s
 => => resolve docker.io/library/node:18-alpine@sha256:0d2712ac2b2c1149391173de670406f6e3dbdb1b2ba44e8530647e623e0e1b17                                                                                          0.0s
 => => sha256:85e3118efd92aa5fcd37d970c324096f73d3f879634eb2c7c9520e1c35c4d0cc 47.32MB / 47.32MB                                                                                                                 1.9s
 => => sha256:3839a37b9e43421a6f49d673a0090820c5ff2f68abd9b6eb86f5f43902e944d5 2.41MB / 2.41MB                                                                                                                   1.8s
 => => sha256:1321f2e94f526bd42ba86c15fa00bcd04e4048f7cd8ae4783437920c3a20dd45 446B / 446B                                                                                                                       0.5s
 => => sha256:0d2712ac2b2c1149391173de670406f6e3dbdb1b2ba44e8530647e623e0e1b17 1.43kB / 1.43kB                                                                                                                   0.0s
 => => sha256:42bc77b5726ae6d9479ea9bc75bff553619ba6e80d7e621a68772a6d3934fb5e 1.16kB / 1.16kB                                                                                                                   0.0s
 => => sha256:ad0efe67fff24bb910680cbcdf597e913aba2989eedef4dec8dbd456cbd50646 6.45kB / 6.45kB                                                                                                                   0.0s
 => => extracting sha256:85e3118efd92aa5fcd37d970c324096f73d3f879634eb2c7c9520e1c35c4d0cc                                                                                                                        0.9s
 => => extracting sha256:3839a37b9e43421a6f49d673a0090820c5ff2f68abd9b6eb86f5f43902e944d5                                                                                                                        0.1s
 => => extracting sha256:1321f2e94f526bd42ba86c15fa00bcd04e4048f7cd8ae4783437920c3a20dd45                                                                                                                        0.0s
 => [2/6] RUN apk add ffmpeg && mkdir /src                                                                                                                                                                       2.8s
 => [3/6] WORKDIR /src                                                                                                                                                                                           0.0s
 => [4/6] COPY ./package.json .                                                                                                                                                                                  0.0s
 => [5/6] RUN npm install                                                                                                                                                                                        0.6s
 => [6/6] COPY . .                                                                                                                                                                                               0.0s
 => exporting to image                                                                                                                                                                                           0.2s
 => => exporting layers                                                                                                                                                                                          0.2s
 => => writing image sha256:b814092034216def81d59ff938d9e7faa4ab9a6078792704bd91b1ee5b588d43                                                                                                                     0.0s
 => => naming to docker.io/library/vimeo-private-downloader:latest                                                                                                                                               0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

$ make start

> vimeodownload@1.0.0 start
> node ./index.js

→ ⚠️  The master.json file is expired or crushed. Please update or remove it from the sequence (broken on 0 position)
npm notice
npm notice New patch version of npm available! 9.5.0 -> 9.5.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.1
npm notice Run npm install -g npm@9.5.1 to update!
npm notice

$ make start

> vimeodownload@1.0.0 start
> node ./index.js

→ 📦 📹 Downloading video segment 0/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 1/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 2/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 3/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 4/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 5/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 6/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 7/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 8/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 9/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 10/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 11/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 12/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 13/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 14/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 15/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 16/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 17/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 18/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 19/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 20/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 21/23 of ./parts/Beluga-test.m4v
→ 📦 📹 Downloading video segment 22/23 of ./parts/Beluga-test.m4v
→ 🏁  ./parts/Beluga-test.m4v - video done
→ 📦 🎧 Downloading audio segment 0/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 1/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 2/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 3/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 4/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 5/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 6/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 7/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 8/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 9/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 10/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 11/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 12/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 13/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 14/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 15/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 16/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 17/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 18/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 19/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 20/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 21/23 of ./parts/Beluga-test.m4a
→ 📦 🎧 Downloading audio segment 22/23 of ./parts/Beluga-test.m4a
→ 🏁  ./parts/Beluga-test.m4a - audio done
→ ⚠️  The master.json file is expired or crushed. Please update or remove it from the sequence (broken on 1 position)
npm notice
npm notice New patch version of npm available! 9.5.0 -> 9.5.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.1
npm notice Run npm install -g npm@9.5.1 to update!
npm notice

$ make combine

> vimeodownload@1.0.0 combine
> sh vimeo-combine.sh

Runing Task 1 - Beluga-test.mp4
npm notice
npm notice New patch version of npm available! 9.5.0 -> 9.5.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.1
npm notice Run npm install -g npm@9.5.1 to update!
npm notice
```

**Comment by andruten** [comment]
@Tusko I've updated the readme :)

**Comment by Tusko** [comment]
Thank you so much!

**Pull request merged**
