### PR TITLE
Create run.sh

### PR DESCRIPTION
**Pull request by ftitreefly**
A candy bash for combine videos

### CODE REVIEW

**Comment by Tusko** [comment]
@ftitreefly thank you for PR.

I've fixed paths for downloading to `./parts/` folder.
I don't have good skills in bash, so can you fix the paths to:
 - input files `./parts/`
 - converted files `./converted/`

**Comment by Tusko** [comment]
@ftitreefly Perfect! Thank you

**Comment by virtual-idealist** [comment]
I keep getting an error trying to combine the files.

image

I'm using the code from 3/22

ls parts/*.m4v | sed 's/.m4v//g;s/parts\///g;s/"/\\"/g;' | \
awk '{printf("echo Runing Task %d - \"%s.mp4\"\n", NR,$0)}{m4a="parts/"$0".m4a";m4v="parts/"$0".m4v";mp4="converted/"$0".mp4"; printf("ffmpeg -y -loglevel quiet -i \"%s\" -i \"%s\" -c copy \"%s\"\n", m4a, m4v, mp4) }' \
> combine.sh

chmod +x combine.sh

./combine.sh

**Comment by ftitreefly** [comment]
@virtual-idealist  try running codes in Linux/MacOS.

**Comment by virtual-idealist** [comment]
I don't have either of those operating systems :(

**Pull request merged**
